
BINARY = elfconv

BUILD = yes

BINPLACE = tools/bin

BINARYTYPE = build

INCLUDES += $(SRCROOT)/os/uefi/include;

OBJS = elfc32.o     \
       elfc64.o     \
       elfconv.o    \

include $(SRCROOT)/os/ka09.mk
